//! One cached, idempotent state file for every command that needs to remember
//! something: `.bbx-state`.
//!
//! Line-oriented and greppable, like `.context-limits` and `.spec-records` in
//! the sibling repos -- not JSON, so the core stays free of `serde` (§C: the
//! deterministic core must build with `--no-default-features`).
//!
//! ```text
//! kind key value
//! pace prefill 1738
//! tok  src/fed/SPEC.md 1023
//! hash src/fed/SPEC.md 8f2a1c...
//! ```
//!
//! IDEMPOTENT: writing unchanged state twice yields a byte-identical file, and
//! reading it back yields the same map. Asserted, because a cache that drifts
//! on rewrite is worse than no cache -- the same guarantee cavespec asserts
//! for `fmt`.

use std::collections::BTreeMap;
use std::hash::{Hash, Hasher};
use std::path::PathBuf;

/// `(kind, key) -> value`. `BTreeMap` so serialisation is ordered, which is
/// what makes the file byte-stable across runs.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct State {
    map: BTreeMap<(String, String), String>,
}

fn path() -> PathBuf {
    PathBuf::from(std::env::var("BBX_STATE").unwrap_or_else(|_| ".bbx-state".into()))
}

impl State {
    /// Read state, or an empty one. A missing file is a cold start, not an
    /// error; a malformed LINE is skipped, but never silently -- an
    /// unparseable file would otherwise read as "nothing cached" forever.
    #[must_use]
    pub fn load() -> Self {
        let mut s = Self::default();
        let Ok(text) = std::fs::read_to_string(path()) else { return s };
        for (n, line) in text.lines().enumerate() {
            if line.starts_with('#') || line.trim().is_empty() {
                continue;
            }
            let mut it = line.splitn(3, ' ');
            match (it.next(), it.next(), it.next()) {
                (Some(k), Some(key), Some(v)) => {
                    s.map.insert((k.into(), key.into()), v.into());
                }
                _ => eprintln!("bbx-state:{}: unparseable line, ignored", n + 1),
            }
        }
        s
    }

    /// Write. Best-effort: a read-only tree must not fail a run over a cache.
    pub fn save(&self) {
        let mut out = String::from("# generated by bbx. Idempotent -- rewriting unchanged state is a no-op.\n");
        for ((kind, key), v) in &self.map {
            out.push_str(&format!("{kind} {key} {v}\n"));
        }
        let _ = std::fs::write(path(), out);
    }

    #[must_use]
    pub fn get(&self, kind: &str, key: &str) -> Option<&str> {
        self.map.get(&(kind.into(), key.into())).map(String::as_str)
    }

    pub fn set(&mut self, kind: &str, key: &str, value: impl Into<String>) {
        self.map.insert((kind.into(), key.into()), value.into());
    }

    #[must_use]
    pub fn get_u64(&self, kind: &str, key: &str) -> Option<u64> {
        self.get(kind, key).and_then(|v| v.parse().ok())
    }

    /// Drop every entry of one kind -- used when a plan is superseded, so a
    /// stale step never outlives the plan that produced it.
    pub fn clear_kind(&mut self, kind: &str) {
        self.map.retain(|(k, _), _| k != kind);
    }

    #[must_use]
    pub fn serialise(&self) -> String {
        self.map.iter().map(|((k, key), v)| format!("{k} {key} {v}\n")).collect()
    }
}

/// Content hash, for cache keys.
///
/// `DefaultHasher` is not stable across Rust releases, which is fine here and
/// nowhere else: a changed hash function means a cache MISS and a recompute,
/// never a wrong answer. It would not be acceptable for anything a gate reads.
#[must_use]
pub fn content_hash(bytes: &[u8]) -> String {
    let mut h = std::collections::hash_map::DefaultHasher::new();
    bytes.hash(&mut h);
    format!("{:016x}", h.finish())
}

/// Cached token count for a file, recomputed only when its content changed.
///
/// # Errors
/// Propagates the read failure -- unreadable is not zero (`.:tokens` V5).
pub fn cached_tokens(st: &mut State, path: &std::path::Path) -> std::io::Result<u64> {
    let bytes = std::fs::read(path)?;
    let key = path.to_string_lossy().to_string();
    let h = content_hash(&bytes);
    if st.get("hash", &key) == Some(h.as_str()) {
        if let Some(n) = st.get_u64("tok", &key) {
            return Ok(n);
        }
    }
    let n = crate::tokens::count(&String::from_utf8_lossy(&bytes)).tokens;
    st.set("hash", &key, h);
    st.set("tok", &key, n.to_string());
    Ok(n)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_and_is_idempotent() {
        let mut a = State::default();
        a.set("pace", "prefill", "1738");
        a.set("tok", "src/fed/SPEC.md", "1023");
        let once = a.serialise();
        let twice = a.clone().serialise();
        assert_eq!(once, twice, "serialising unchanged state must be byte-identical");
        assert_eq!(a.get("pace", "prefill"), Some("1738"));
        assert_eq!(a.get_u64("tok", "src/fed/SPEC.md"), Some(1023));
    }

    #[test]
    fn ordering_is_stable_regardless_of_insertion_order() {
        let mut a = State::default();
        a.set("z", "k", "1");
        a.set("a", "k", "2");
        let mut b = State::default();
        b.set("a", "k", "2");
        b.set("z", "k", "1");
        assert_eq!(a.serialise(), b.serialise(), "order must not leak into the file");
    }

    #[test]
    fn clear_kind_removes_only_that_kind() {
        let mut a = State::default();
        a.set("plan", "1", "x");
        a.set("pace", "prefill", "900");
        a.clear_kind("plan");
        assert!(a.get("plan", "1").is_none());
        assert_eq!(a.get("pace", "prefill"), Some("900"));
    }

    #[test]
    fn content_hash_tracks_content_only() {
        assert_eq!(content_hash(b"abc"), content_hash(b"abc"));
        assert_ne!(content_hash(b"abc"), content_hash(b"abd"));
    }
}
