//! One cached, idempotent state file for every command that needs to remember
//! something: `.sherd-state`.
//!
//! Line-oriented and greppable, like `.context-limits` and `.spec-records` in
//! the sibling repos -- not JSON, so the core stays free of `serde` (§C: the
//! deterministic core must build with `--no-default-features`).
//!
//! ```text
//! kind key value
//! pace prefill 1738
//! tok  src/fed/SPEC.md 1023
//! hash src/fed/SPEC.md 8f2a1c...
//! ```
//!
//! IDEMPOTENT: writing unchanged state twice yields a byte-identical file, and
//! reading it back yields the same map. Asserted, because a cache that drifts
//! on rewrite is worse than no cache -- the same guarantee microlith asserts
//! for `fmt`.

use std::collections::BTreeMap;
use std::hash::{Hash, Hasher};
use std::path::PathBuf;

/// `(kind, key) -> value`. `BTreeMap` so serialisation is ordered, which is
/// what makes the file byte-stable across runs.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct State {
    map: BTreeMap<(String, String), String>,
    /// Where this state was read from, and where [`Self::save`] writes.
    ///
    /// Carried rather than re-resolved, so a `State` is a value and not a
    /// handle on one ambient file. Reading `SHERD_STATE` inside `save` meant
    /// every test in the process shared one file: they wrote `obs` rows,
    /// `derived_prefill` branched on how many existed, and which lines
    /// executed depended on what a previous run left behind (`src/ollama:B8`).
    ///
    /// `std::env::set_var` is unsafe under edition 2024 and this crate
    /// FORBIDS unsafe, so a per-test env var was never available -- the path
    /// had to become a parameter (`src/ollama:V19`).
    path: PathBuf,
}

/// The default state file: `SHERD_STATE`, else `.sherd-state` beside the repo.
///
/// Read at the EDGE only. Everything below takes the path as a value, the
/// same split `tdd::cargo_bin`/`gate_with` uses for the toolchain.
#[must_use]
pub fn default_path() -> PathBuf {
    PathBuf::from(
        std::env::var("SHERD_STATE").unwrap_or_else(|_| ".sherd-state".into()),
    )
}

impl State {
    /// Read state, or an empty one. A missing file is a cold start, not an
    /// error; a malformed LINE is skipped, but never silently -- an
    /// unparsable file would otherwise read as "nothing cached" forever.
    #[must_use]
    pub fn load() -> Self {
        Self::at(default_path())
    }

    /// Read state from an EXPLICIT path.
    ///
    /// What makes the suite hermetic: a test hands its own temp file and
    /// shares nothing with the tests running beside it.
    #[must_use]
    pub fn at(path: impl Into<PathBuf>) -> Self {
        let path = path.into();
        let mut s = Self {
            path: path.clone(),
            ..Self::default()
        };
        let Ok(text) = std::fs::read_to_string(&path) else {
            return s;
        };
        for (n, line) in text.lines().enumerate() {
            if line.starts_with('#') || line.trim().is_empty() {
                continue;
            }
            let mut it = line.splitn(3, ' ');
            match (it.next(), it.next(), it.next()) {
                (Some(k), Some(key), Some(v)) => {
                    s.map.insert((k.into(), unescape_key(key)), v.into());
                }
                _ => {
                    eprintln!("sherd-state:{}: unparsable line, ignored", n + 1)
                }
            }
        }
        s
    }

    /// Write. Best-effort: a read-only tree must not fail a run over a cache.
    pub fn save(&self) {
        // Through `serialise`, not a second loop of its own. The two had
        // drifted -- escaping the key in `serialise` changed nothing because
        // the WRITE path never called it (B1), which is `.:src/fed:B13`'s two
        // readings of one rule inside a nine-line function.
        let out = format!(
            "# generated by sherd. Idempotent -- rewriting unchanged state is a no-op.\n{}",
            self.serialise()
        );
        let _ = std::fs::write(&self.path, out);
    }

    #[must_use]
    pub fn get(&self, kind: &str, key: &str) -> Option<&str> {
        self.map.get(&(kind.into(), key.into())).map(String::as_str)
    }

    pub fn set(&mut self, kind: &str, key: &str, value: impl Into<String>) {
        self.map.insert((kind.into(), key.into()), value.into());
    }

    #[must_use]
    pub fn get_u64(&self, kind: &str, key: &str) -> Option<u64> {
        self.get(kind, key).and_then(|v| v.parse().ok())
    }

    /// Drop every entry of one kind -- used when a plan is superseded, so a
    /// stale step never outlives the plan that produced it.
    pub fn clear_kind(&mut self, kind: &str) {
        self.map.retain(|(k, _), _| k != kind);
    }

    /// Every value of one kind.
    #[must_use]
    pub fn all(&self, kind: &str) -> Vec<String> {
        self.map
            .iter()
            .filter(|((k, _), _)| k == kind)
            .map(|(_, v)| v.clone())
            .collect()
    }

    /// Append one entry to an ORDERED, capped log, deduplicated by `dedup`.
    ///
    /// The key carries a zero-padded sequence, so lexical order IS insertion
    /// order and the cap drops the genuinely oldest. A plain key-order trim
    /// cannot do that: its only ordering is the key's own, and the one real
    /// caller keys by CONTENT HASH, which carries no time at all (B2).
    ///
    /// Idempotent, and that is what lets this avoid a timestamp: an entry
    /// whose `dedup` is already present is not re-appended, so recording the
    /// same observation twice leaves the file byte-identical. A clock would
    /// change the file when nothing changed, which is not a cache.
    pub fn push(&mut self, log: Log, dedup: &str, value: impl Into<String>) {
        let kind = log.kind;
        if self.find_key(kind, dedup).is_some() {
            return;
        }
        self.set(kind, &format!("{:08}-{dedup}", self.next_seq(kind)), value);
        let ordered = self.oldest_first(kind);
        let over = ordered.len().saturating_sub(log.cap);
        for k in ordered.into_iter().take(over) {
            self.map.remove(&(kind.to_string(), k));
        }
    }

    /// The sequence the next entry of a kind gets.
    ///
    /// MAX, not the last key's: a file written before ordered keys existed
    /// holds bare content hashes, and `ff78..` sorts after `00000000-..`, so
    /// reading the last key's sequence found none and every append restarted
    /// at zero. An unsequenced key is older than all of them, which is true --
    /// it was written first.
    fn next_seq(&self, kind: &str) -> u64 {
        self.keys_of(kind)
            .iter()
            .filter_map(|k| seq_of(k))
            .max()
            .map_or(0, |n| n.saturating_add(1))
    }

    /// The full key an ordered entry was stored under, found by its `dedup`.
    #[must_use]
    pub fn find_key(&self, kind: &str, dedup: &str) -> Option<String> {
        let suffix = format!("-{dedup}");
        self.keys_of(kind)
            .into_iter()
            .find(|k| k.ends_with(&suffix))
    }

    /// Every key of one kind, oldest first.
    ///
    /// By SEQUENCE, not by the key's own bytes: a legacy bare hash like
    /// `ff7833..` sorts after `00000000-..` lexically, so plain map order put
    /// the oldest entries LAST and the cap evicted the newest. `None` orders
    /// before `Some` in Rust, which is exactly right here -- an unsequenced
    /// entry predates every sequenced one.
    fn oldest_first(&self, kind: &str) -> Vec<String> {
        let mut keys = self.keys_of(kind);
        keys.sort_by_key(|k| (seq_of(k), k.clone()));
        keys
    }

    /// Every key of one kind, in the map's order, which is lexical.
    fn keys_of(&self, kind: &str) -> Vec<String> {
        self.map
            .keys()
            .filter(|(k, _)| k == kind)
            .map(|(_, key)| key.clone())
            .collect()
    }

    #[must_use]
    pub fn serialise(&self) -> String {
        self.map
            .iter()
            .map(|((k, key), v)| format!("{k} {} {v}\n", escape_key(key)))
            .collect()
    }
}

/// The log an ordered entry is appended to: which kind, and how many to keep.
///
/// A struct because `kind` and `cap` describe the LOG and travel together,
/// while `dedup` and `value` describe the ENTRY. Passing all four positionally
/// is the five-argument helper this repo has already written once and
/// reverted -- one lint traded for a worse one.
#[derive(Debug, Clone, Copy)]
pub struct Log<'a> {
    /// The kind these entries share.
    pub kind: &'a str,
    /// How many to keep; the oldest beyond this are evicted.
    pub cap: usize,
}

impl<'a> Log<'a> {
    /// One log: which kind, and how many to keep.
    #[must_use]
    pub const fn new(kind: &'a str, cap: usize) -> Self {
        Self { kind, cap }
    }
}

/// The sequence an ordered key opens with, if it has one.
fn seq_of(key: &str) -> Option<u64> {
    key.split_once('-').and_then(|(n, _)| n.parse().ok())
}
/// A key, safe to sit in the middle field of `kind key value`.
///
/// V1: the VALUE may contain spaces -- an `obs` row carries a whole telemetry
/// line -- so the parser splits three and the key is the middle field. A key
/// with a space silently became its own first word, and everything after it
/// joined the value (B1). `%` is escaped first, or unescaping would be
/// ambiguous.
fn escape_key(key: &str) -> String {
    key.replace('%', "%25").replace(' ', "%20")
}

/// The inverse of [`escape_key`]. `%20` before `%25`, so a literal `%20`
/// written as `%2520` comes back as `%20` and not as a space.
fn unescape_key(key: &str) -> String {
    key.replace("%20", " ").replace("%25", "%")
}

/// Content hash, for cache keys.
///
/// `DefaultHasher` is not stable across Rust releases, which is fine here and
/// nowhere else: a changed hash function means a cache MISS and a recompute,
/// never a wrong answer. It would not be acceptable for anything a gate reads.
#[must_use]
pub fn content_hash(bytes: &[u8]) -> String {
    let mut h = std::collections::hash_map::DefaultHasher::new();
    bytes.hash(&mut h);
    format!("{:016x}", h.finish())
}

/// Cached token count for a file, recomputed only when its content changed.
///
/// # Errors
/// Propagates the read failure -- unreadable is not zero (`.:tokens` V5).
pub fn cached_tokens(
    st: &mut State,
    path: &std::path::Path,
) -> std::io::Result<u64> {
    let bytes = std::fs::read(path)?;
    let key = path.to_string_lossy().to_string();
    let h = content_hash(&bytes);
    if st.get("hash", &key) == Some(h.as_str())
        && let Some(n) = st.get_u64("tok", &key)
    {
        return Ok(n);
    }
    let n = crate::tokens::count(&String::from_utf8_lossy(&bytes)).tokens;
    st.set("hash", &key, h);
    st.set("tok", &key, n.to_string());
    Ok(n)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `cached_tokens` is a CACHE, and a cache that never hits is a slow
    /// counter while a cache that never misses is a wrong one.
    ///
    /// `State::at` rather than `State::load`, so this touches no ambient
    /// `.sherd-state`. `.coverage` records the suite's coverage flapping
    /// because tests share that one file, and adding another writer to it
    /// would make a measurement problem worse to fix a coverage number.
    #[test]
    fn counting_a_file_twice_hits_the_cache_and_a_changed_file_misses() {
        assert_eq!(cache_hits_then_misses(), Ok(()));
    }

    /// A file and a state file, both unique per INSTANCE (`src/review:V6`).
    fn scratch_pair(tag: &str) -> (std::path::PathBuf, std::path::PathBuf) {
        use std::sync::atomic::{AtomicUsize, Ordering};
        static N: AtomicUsize = AtomicUsize::new(0);
        let n = N.fetch_add(1, Ordering::Relaxed);
        let d = std::env::temp_dir();
        let pid = std::process::id();
        (
            d.join(format!("sherd-{tag}-{pid}-{n}.md")),
            d.join(format!("sherd-{tag}-{pid}-{n}.state")),
        )
    }

    /// V2: `set` -> `save` -> `load` -> `get` returns what was set.
    ///
    /// B1 is the absence of this. Every loop label contains a space --
    /// `1 red-test`, `2 green`, `5 blind judge` -- so the per-label pace
    /// model was WRITE-ONLY from the day it was built, and `predict_for`
    /// silently fell back to the default on every step.
    #[test]
    fn a_key_with_a_space_survives_the_round_trip() {
        assert_eq!(round_trips(), Ok(()));
    }

    /// Every shape a key takes here, plus the escape character itself.
    const KEYS: &[(&str, &str, &str)] = &[
        ("gen", "1 red-test", "2342"),
        ("gen", "5 blind judge", "700"),
        ("gen", "monolith", "999"),
        ("score", "src/fed.tried", "3"),
        ("gen", "100% sure", "1"),
        ("gen", "already %20 escaped", "2"),
    ];

    fn round_trips() -> Result<(), String> {
        let (_f, p) = scratch_pair("roundtrip");
        let mut st = State::at(&p);
        for (kind, key, val) in KEYS {
            st.set(kind, key, *val);
        }
        st.save();
        assert_all_readable(&State::at(&p));
        let _ = std::fs::remove_file(&p);
        Ok(())
    }

    fn assert_all_readable(back: &State) {
        for (kind, key, val) in KEYS {
            assert_eq!(
                back.get(kind, key),
                Some(*val),
                "`{key}` must read back as it was written"
            );
        }
    }

    #[test]
    fn a_value_may_still_contain_spaces() {
        // The reason the key is the middle field and not the last: an `obs`
        // row's VALUE is a whole telemetry line. Escaping the key must not
        // disturb that.
        let (_f, p) = scratch_pair("obsvalue");
        let mut st = State::at(&p);
        st.set("obs", "deadbeef", "1 red-test 8377 900 2342 400 0");
        st.save();
        assert_eq!(
            State::at(&p).get("obs", "deadbeef"),
            Some("1 red-test 8377 900 2342 400 0"),
            "the value keeps its spaces"
        );
        let _ = std::fs::remove_file(&p);
    }

    fn cache_hits_then_misses() -> Result<(), String> {
        let (f, s) = scratch_pair("cache");
        std::fs::write(&f, "hello world").map_err(|e| e.to_string())?;
        let mut st = State::at(&s);
        let first = cached_tokens(&mut st, &f).map_err(|e| e.to_string())?;
        let key = f.to_string_lossy().to_string();
        assert!(st.get("hash", &key).is_some(), "the hash is recorded");
        let again = cached_tokens(&mut st, &f).map_err(|e| e.to_string())?;
        assert_eq!(first, again, "identical content, identical count");
        // Changed content must MISS -- a cache keyed on the path alone would
        // return a stale count for an edited file, and every budget and
        // ceiling in this repo is computed from these numbers.
        std::fs::write(&f, "hello world, and a good deal more text besides")
            .map_err(|e| e.to_string())?;
        let after = cached_tokens(&mut st, &f).map_err(|e| e.to_string())?;
        assert!(after > first, "an edited file recounts: {first} -> {after}");
        let _ = std::fs::remove_file(&f);
        let _ = std::fs::remove_file(&s);
        Ok(())
    }

    #[test]
    fn an_unreadable_file_is_an_error_not_a_zero() {
        // V48 through `cached_tokens`: a file that cannot be read must not
        // silently contribute zero tokens to a budget.
        let mut st = State::at(std::env::temp_dir().join("sherd-nonexistent"));
        let missing = std::path::Path::new("/definitely/not/here.md");
        assert!(cached_tokens(&mut st, missing).is_err());
    }

    #[test]
    fn round_trips_and_is_idempotent() {
        let mut a = State::default();
        a.set("pace", "prefill", "1738");
        a.set("tok", "src/fed/SPEC.md", "1023");
        let once = a.serialise();
        let twice = a.clone().serialise();
        assert_eq!(
            once, twice,
            "serialising unchanged state must be byte-identical"
        );
        assert_eq!(a.get("pace", "prefill"), Some("1738"));
        assert_eq!(a.get_u64("tok", "src/fed/SPEC.md"), Some(1023));
    }

    #[test]
    fn ordering_is_stable_regardless_of_insertion_order() {
        let mut a = State::default();
        a.set("z", "k", "1");
        a.set("a", "k", "2");
        let mut b = State::default();
        b.set("a", "k", "2");
        b.set("z", "k", "1");
        assert_eq!(
            a.serialise(),
            b.serialise(),
            "order must not leak into the file"
        );
    }

    #[test]
    fn clear_kind_removes_only_that_kind() {
        let mut a = State::default();
        a.set("plan", "1", "x");
        a.set("pace", "prefill", "900");
        a.clear_kind("plan");
        assert!(a.get("plan", "1").is_none());
        assert_eq!(a.get("pace", "prefill"), Some("900"));
    }

    /// `B2`, on the numbers that row records: keyed by CONTENT HASH the
    /// retained set was a hash-sampled slice of ALL history, not a recency
    /// window. Measured before the fix -- of 700 observations capped at 200,
    /// 62 survivors came from the FIRST two hundred and only 63 from the last.
    ///
    /// `push` makes the key carry a sequence, so the cap drops the
    /// genuinely oldest and the window is the last `cap` appended.
    #[test]
    fn an_ordered_log_keeps_the_newest_not_a_hash_sample() {
        let mut a = State::default();
        for i in 0..700 {
            let line = format!("row {i}");
            let k = content_hash(line.as_bytes());
            a.push(Log::new("obs", 200), &k, line);
        }
        let kept: Vec<usize> = a
            .all("obs")
            .iter()
            .filter_map(|l| l.strip_prefix("row ")?.parse().ok())
            .collect();
        assert_eq!(kept.len(), 200, "the cap holds");
        assert!(
            kept.iter().all(|i| *i >= 500),
            "every retained row is from the last 200 appended; oldest kept \
             was {:?}",
            kept.iter().min()
        );
    }

    /// The dedup that lets an ordered log avoid a timestamp: re-recording the
    /// same observation leaves the file byte-identical, so a state file that
    /// changed when nothing changed cannot happen.
    #[test]
    fn pushing_the_same_entry_twice_changes_nothing() {
        let mut a = State::default();
        a.push(Log::new("obs", 10), "deadbeef", "row");
        let once = a.serialise();
        a.push(Log::new("obs", 10), "deadbeef", "row");
        assert_eq!(a.serialise(), once, "a repeat append is a no-op");
        assert_eq!(a.all("obs").len(), 1);
    }

    /// A caller that only has the dedup key can still find what it stored,
    /// which is what `record_obs_in`'s idempotence rests on.
    #[test]
    fn an_ordered_entry_is_findable_by_its_dedup_key() {
        let mut a = State::default();
        a.push(Log::new("obs", 10), "cafe", "first");
        a.push(Log::new("obs", 10), "f00d", "second");
        let k = a.find_key("obs", "f00d").unwrap_or_default();
        assert!(k.ends_with("-f00d"), "the dedup key is the suffix: {k}");
        assert_eq!(a.get("obs", &k), Some("second"));
        assert_eq!(a.find_key("obs", "absent"), None);
    }

    /// A file written before ordered keys existed holds bare content hashes.
    /// Appending to it must not restart the sequence at zero -- `ff78...`
    /// sorts AFTER `00000000-...`, so reading the last key's sequence found
    /// none every time.
    ///
    /// An unsequenced entry is older than every sequenced one, which is true:
    /// it was written first, and it is evicted first.
    #[test]
    fn an_ordered_log_resumes_over_keys_written_before_it_existed() {
        let mut a = State::default();
        for legacy in ["00457224e0ad913c", "ff7833f252862eb6"] {
            a.set("obs", legacy, format!("legacy {legacy}"));
        }
        a.push(Log::new("obs", 10), "aaaa", "new one");
        a.push(Log::new("obs", 10), "bbbb", "new two");
        let keys: Vec<Option<String>> = ["aaaa", "bbbb"]
            .iter()
            .map(|d| a.find_key("obs", d))
            .collect();
        assert_eq!(
            keys,
            vec![
                Some("00000000-aaaa".to_string()),
                Some("00000001-bbbb".to_string())
            ],
            "the sequence advances rather than restarting"
        );
        // And the legacy rows go FIRST when the cap bites.
        a.push(Log::new("obs", 3), "cccc", "new three");
        assert_eq!(a.all("obs").len(), 3);
        assert!(
            a.find_key("obs", "cccc").is_some()
                && a.get("obs", "00457224e0ad913c").is_none(),
            "an unsequenced row is the oldest and is dropped first"
        );
    }

    #[test]
    fn content_hash_tracks_content_only() {
        assert_eq!(content_hash(b"abc"), content_hash(b"abc"));
        assert_ne!(content_hash(b"abc"), content_hash(b"abd"));
    }
}

#[cfg(test)]
mod path_tests {
    use super::*;

    fn tmp(tag: &str) -> PathBuf {
        use std::sync::atomic::{AtomicUsize, Ordering};
        static N: AtomicUsize = AtomicUsize::new(0);
        let n = N.fetch_add(1, Ordering::Relaxed);
        // Unique per INSTANCE, not per process -- `src/review:V6`, learned
        // when two fixtures sharing a tag deleted each other's directory.
        std::env::temp_dir()
            .join(format!("sherd-state-{tag}-{}-{n}", std::process::id()))
    }

    #[test]
    fn a_state_remembers_where_it_came_from() {
        let p = tmp("roundtrip");
        let mut a = State::at(&p);
        a.set("obs", "k", "v");
        a.save();
        let b = State::at(&p);
        assert_eq!(b.get("obs", "k"), Some("v"), "save must write to `path`");
        let _ = std::fs::remove_file(&p);
    }

    #[test]
    fn two_states_at_different_paths_share_nothing() {
        // THE POINT of T13. Before this, every test in the process wrote the
        // same `.sherd-state`, so `derived_prefill` branched on what a previous
        // test had left and coverage measured 75.26-75.35% for one unchanged
        // tree (`src/ollama:B8`).
        let (p, q) = (tmp("iso-a"), tmp("iso-b"));
        let mut a = State::at(&p);
        a.set("gen", "1 red", "2500");
        a.save();
        let b = State::at(&q);
        assert_eq!(b.get("gen", "1 red"), None, "a fresh path is a cold start");
        let _ = std::fs::remove_file(&p);
        let _ = std::fs::remove_file(&q);
    }

    #[test]
    fn a_missing_file_is_a_cold_start_not_an_error() {
        let s = State::at(tmp("absent"));
        assert_eq!(s.all("obs").len(), 0);
    }

    #[test]
    fn the_default_path_is_read_from_the_environment_at_the_edge() {
        // `SHERD_STATE`, else `.sherd-state`. Read HERE and nowhere below, which
        // is what let the path become a parameter -- `std::env::set_var` is
        // unsafe under edition 2024 and this crate forbids unsafe, so a
        // per-test env var was never an option (`src/ollama:V19`).
        let p = default_path();
        assert!(p.to_string_lossy().contains("sherd-state"), "{p:?}");
    }
}
